### ISSUE TITLE
Connectathon 35 issue - Seperate buttons for registration

### ISSUE THREAD

**Issue by dancinnamon-okta** [Evernorth/hl7-fhir-udap-client-test-ui#6]
In touchstone, test scenarios are split between B2B and B2C.  When a B2B test is executed, it looks for a specific B2B registration, and subsequently for B2C, it looks for a B2C registration.  This can cause issues with the current implementation because we always register both at the same time, and touchstone might inadvertantly fail our implementation because we sent the "wrong" registration first.  

This issue/enhancement is to simply have an additional button that allows us to send through the registration that we want (b2b or b2c).

**Comment by TomLoomis-Evernorth** [comment]
Added during connectathon 35.  Also added a delete registration button.
